### ISSUE TITLE
tag ID reported rather than animal ID

### ISSUE THREAD

**Issue by sarahcd** [movestore/Point-Cluster-Detection#3]
Records for an individual animal can come from multiple tags at once and across time.
* add the animal.id/individual.local.identifier to Track Attributes rather than tagID, to avoid analysis mistaking tags for animals and retain the users' animal IDs.
* make sure all the ID calculations are based on the animal ID, not tag ID.

**Comment by andreakoelzsch** [comment]
The focus on tagID comes from Corinne, for here work I have developed the App. animalID is in all the tables as well, but a little bit further down. I see you point that this is not consistent with the other Apps an philosophy in MoveApps. For the next update of the App, I will discuss that with Corinne.
