### ISSUE TITLE
difftime and udunits not the same strings :(

### ISSUE THREAD

**Issue by smthfrmn** [movestore/Point-Cluster-Detection#9]
Okay, so [move2](https://gitlab.com/bartk/move2/-/blob/main/R/mt_distance.R#L60) is using `udunits` when calling the function `mt_time_lag`, which expects the minutes string to be either `min` or `minutes` but not `mins`. Unfortunately, `difftime` uses `secs`, `mins`, `hours` etc, which is the string that we pass to `dur_unit` and `gap_unit`. This is causing this error to be thrown in the app, when the user selects a unit of `mins`:

```r
> units::as_units("mins", mode = "standard")
Error: In ‘mins’, ‘mins’ is not recognized by udunits.

See a table of valid unit symbols and names with valid_udunits().
Custom user-defined units can be added with install_unit().

See a table of valid unit prefixes with valid_udunits_prefixes().
Prefixes will automatically work with any user-defined unit.
```

Coming from (and possibly elsewhere in the app): https://github.com/movestore/Point-Cluster-Detection/blob/main/RFunction.R#L333

I think ideally this would get handled in `move2`, so that the user wouldn't have to handle if they are passing the unit string to a `difftime` object or to a `move2` function. But I'm not sure the best way to go about that.

@andreakoelzsch I've shared the workflow with you, if you would like to see in action

**Comment by andreakoelzsch** [comment]
@smthfrmn Hi Smith, thanks for looking into the error directly! It would be great if you can make a pull request how to fix this issue in the code. Is it more than just the change of mins to min? I can pass on the idea of passing on to difftime to the move2 pacakge develoepr.

**Comment by andreakoelzsch** [comment]
@annescharf Hi Anne, after reading this again, I realise that simply changing mins/min is not the solution (I can and will solve it with some ifs maybe). But this might be a more general issue for move2... i.e. that some packages need "min" and others "mins".

**Comment by smthfrmn** [comment]
@andreakoelzsch I agree, but I can make the update for this app in the meantime

**Comment by andreakoelzsch** [comment]
solved by PR from @smthfrmn. Thanks a lot!
